/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ProjectRouteRouteImport } from './app/project/route'
import { Route as AboutRouteRouteImport } from './app/about/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as ProjectVerchiaRouteImport } from './app/project/verchia'
import { Route as ProjectPradelnaRouteImport } from './app/project/pradelna'
import { Route as ProjectManshausenRouteImport } from './app/project/manshausen'
import { Route as ProjectDialogExeRouteImport } from './app/project/dialog-exe'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectVerchiaRoute = ProjectVerchiaRouteImport.update({
  id: '/verchia',
  path: '/verchia',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectPradelnaRoute = ProjectPradelnaRouteImport.update({
  id: '/pradelna',
  path: '/pradelna',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectManshausenRoute = ProjectManshausenRouteImport.update({
  id: '/manshausen',
  path: '/manshausen',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectDialogExeRoute = ProjectDialogExeRouteImport.update({
  id: '/dialog-exe',
  path: '/dialog-exe',
  getParentRoute: () => ProjectRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/project': typeof ProjectRouteRouteWithChildren
  '/project/dialog-exe': typeof ProjectDialogExeRoute
  '/project/manshausen': typeof ProjectManshausenRoute
  '/project/pradelna': typeof ProjectPradelnaRoute
  '/project/verchia': typeof ProjectVerchiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/project': typeof ProjectRouteRouteWithChildren
  '/project/dialog-exe': typeof ProjectDialogExeRoute
  '/project/manshausen': typeof ProjectManshausenRoute
  '/project/pradelna': typeof ProjectPradelnaRoute
  '/project/verchia': typeof ProjectVerchiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/project': typeof ProjectRouteRouteWithChildren
  '/project/dialog-exe': typeof ProjectDialogExeRoute
  '/project/manshausen': typeof ProjectManshausenRoute
  '/project/pradelna': typeof ProjectPradelnaRoute
  '/project/verchia': typeof ProjectVerchiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/project'
    | '/project/dialog-exe'
    | '/project/manshausen'
    | '/project/pradelna'
    | '/project/verchia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/project'
    | '/project/dialog-exe'
    | '/project/manshausen'
    | '/project/pradelna'
    | '/project/verchia'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/project'
    | '/project/dialog-exe'
    | '/project/manshausen'
    | '/project/pradelna'
    | '/project/verchia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRoute
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/verchia': {
      id: '/project/verchia'
      path: '/verchia'
      fullPath: '/project/verchia'
      preLoaderRoute: typeof ProjectVerchiaRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/pradelna': {
      id: '/project/pradelna'
      path: '/pradelna'
      fullPath: '/project/pradelna'
      preLoaderRoute: typeof ProjectPradelnaRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/manshausen': {
      id: '/project/manshausen'
      path: '/manshausen'
      fullPath: '/project/manshausen'
      preLoaderRoute: typeof ProjectManshausenRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/dialog-exe': {
      id: '/project/dialog-exe'
      path: '/dialog-exe'
      fullPath: '/project/dialog-exe'
      preLoaderRoute: typeof ProjectDialogExeRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
  }
}

interface ProjectRouteRouteChildren {
  ProjectDialogExeRoute: typeof ProjectDialogExeRoute
  ProjectManshausenRoute: typeof ProjectManshausenRoute
  ProjectPradelnaRoute: typeof ProjectPradelnaRoute
  ProjectVerchiaRoute: typeof ProjectVerchiaRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectDialogExeRoute: ProjectDialogExeRoute,
  ProjectManshausenRoute: ProjectManshausenRoute,
  ProjectPradelnaRoute: ProjectPradelnaRoute,
  ProjectVerchiaRoute: ProjectVerchiaRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRoute,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
