/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SnoRouteImport } from './app/sno'
import { Route as NfeRouteImport } from './app/nfe'
import { Route as ManshausenRouteImport } from './app/manshausen'
import { Route as DxRouteImport } from './app/dx'
import { Route as IndexRouteImport } from './app/index'

const SnoRoute = SnoRouteImport.update({
  id: '/sno',
  path: '/sno',
  getParentRoute: () => rootRouteImport,
} as any)
const NfeRoute = NfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => rootRouteImport,
} as any)
const ManshausenRoute = ManshausenRouteImport.update({
  id: '/manshausen',
  path: '/manshausen',
  getParentRoute: () => rootRouteImport,
} as any)
const DxRoute = DxRouteImport.update({
  id: '/dx',
  path: '/dx',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dx': typeof DxRoute
  '/manshausen': typeof ManshausenRoute
  '/nfe': typeof NfeRoute
  '/sno': typeof SnoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dx': typeof DxRoute
  '/manshausen': typeof ManshausenRoute
  '/nfe': typeof NfeRoute
  '/sno': typeof SnoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dx': typeof DxRoute
  '/manshausen': typeof ManshausenRoute
  '/nfe': typeof NfeRoute
  '/sno': typeof SnoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dx' | '/manshausen' | '/nfe' | '/sno'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dx' | '/manshausen' | '/nfe' | '/sno'
  id: '__root__' | '/' | '/dx' | '/manshausen' | '/nfe' | '/sno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DxRoute: typeof DxRoute
  ManshausenRoute: typeof ManshausenRoute
  NfeRoute: typeof NfeRoute
  SnoRoute: typeof SnoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sno': {
      id: '/sno'
      path: '/sno'
      fullPath: '/sno'
      preLoaderRoute: typeof SnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfe': {
      id: '/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof NfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manshausen': {
      id: '/manshausen'
      path: '/manshausen'
      fullPath: '/manshausen'
      preLoaderRoute: typeof ManshausenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dx': {
      id: '/dx'
      path: '/dx'
      fullPath: '/dx'
      preLoaderRoute: typeof DxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DxRoute: DxRoute,
  ManshausenRoute: ManshausenRoute,
  NfeRoute: NfeRoute,
  SnoRoute: SnoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
